// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sihftxsyigiaucbiplej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaGZ0eHN5aWdpYXVjYmlwbGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTE0NzcsImV4cCI6MjA1NTI2NzQ3N30.jLuZMWyC06g-01UvM2BF4wGYqFDwitf429CWLslk8vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);